#!/bin/sh

function echodebug(){
echo Debug: "$@" >&2
}

function OpenFILEFolder(){ xdg-open $(dirname "$FILE"); }

function ShowFILEAsDbus(){
[ -n "$DebugFlag" ]&& echodebug ShowFILEAsDbus FILE="$FILE"
dbus-send --session --print-reply --dest=org.freedesktop.FileManager1 --type=method_call /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:"file://$FILE" string:""
}

function GetFILESLISTfromEXECLINE(){
[ -n "$DebugFlag" ]&& echodebug GetFILESLISTfromEXECLINE EXECLINE="$EXECLINE"
FILESLIST=''
while read A;do
  #[ -n "$DebugFlag" ]&& echodebug A="$A"
  [ -e "$A" ]|| A=`which 2>/dev/null "$A"`
  [ -n "$A" ]&& FILESLIST=$FILESLIST$A$'\n'
done <<<$(eval "for word in $EXECLINE;do echo \$word;done")
}

function FILESLISTfromDesktopFILE(){
[ -n "$DebugFlag" ]&& echodebug FILESLISTfromDesktopFILE FILE="$FILE"
EXEprefix='Exec='
EXECLINE=`grep -m 1 -E "^$EXEprefix" "$FILE"`||{ echo $EXEprefix not found >&2; return 1; }
EXECLINE=${EXECLINE#$EXEprefix}
GetFILESLISTfromEXECLINE
}

function YadButtonWord(){
echo '--field='\'"$1":btn\' \''bash --posix -c "kill -n 15 $YAD_PID;echo '"$2"\"\'
}


#--------------START------------


[ -z "$1" ]&&{ echo specify symlink or .desktop;exit 1; }
[ -e "$1" ]||{ echo specify exist file;exit 1; }
[ -d "$1" ]&&{ echo "you specify directory, exit";exit 1; }

DebugFlag=y

FILE=$1;FILESLIST=''
if [ -L "$FILE" ];then
 [ -n "$DebugFlag" ]&& echodebug 'get symlink'
 FILESLIST=`readlink -e "$FILE"`
elif grep -i 'desktop$' <<<"$FILE";then
 [ -n "$DebugFlag" ]&& echodebug 'get desktop'
 FILESLISTfromDesktopFILE||exit $?
fi
[ -n "$DebugFlag" ]&& echodebug FILESLIST="$FILESLIST";
[ -z "$FILESLIST" ]&&exit 1

FILESLIST="$(echo "$FILESLIST"|uniq)"
[ -n "$DebugFlag" ]&& echodebug uniq FILESLIST="$FILESLIST"

N=0
while read foundedfile ;do
[ -n "$foundedfile" ]&&
N=$((N+1))&& YadButtonLine=$(YadButtonWord "$foundedfile" $N)' '$YadButtonLine
done<<<"$FILESLIST"

[ -n "$DebugFlag" ]&& echodebug YadButtonLine="$YadButtonLine"
[ -n "$DebugFlag" ]&& echodebug N=$N

[ $N = 1 ]||N=$(eval yad  --on-top --mouse --undecorated --skip-taskbar --close-on-unfocus --no-buttons  --form  $YadButtonLine)
[ -z "$N" ] && N=1
[ -n "$DebugFlag" ]&& echodebug N=$N
[ -z "$FILESLIST" ]&&exit 1
[ -n "$DebugFlag" ]&& echodebug FILESLIST="$FILESLIST"
FILE=`echo "$FILESLIST"|head -n $N|tail -n 1`
ShowFILEAsDbus||OpenFILEFolder
